name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - id: backend-deploy-create_bingo
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: python-djurbingo-create-bingo-cf
          description: Creates a bingo competition
          region: europe-west1
          source_dir: backend/create_bingo
          entry_point: create_bingo
          runtime: python39
          timeout: 60
          max_instances: 1
          https_trigger_security_level: secure_always

      - id: frontend-build
        working-directory: djurbingo-web
        run: npm ci && npm run build

      - id: frontend-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DJURBINGO }}'
          channelId: live
          projectId: djurbingo
